import "./globals.css";

export const metadata = {
    title: "Guess the Star",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <nav className="container w-full h-20 border-solid border-b-2 border-white flex items-center justify-between px-5">
                    <h1>Name of the App</h1>
                    <div className="visible md:hidden">Menu</div>
                    <ul className="hidden md:visible md:flex gap-6">
                        <li>
                            <a>Help</a>
                        </li>
                        <li>
                            <a>Stats</a>
                        </li>
                        <li>
                            <a>Settings</a>
                        </li>
                    </ul>
                </nav>
                {children}
            </body>
        </html>
    );
}
